name: Manual Deploy to Canada Instance
on: [workflow_dispatch]
jobs:
  deploy:
    name: Deploy production code to Canada Instance 
    runs-on: ubuntu-latest
    steps:
      - name: SSH into instance and pull repository
        run: |
          echo "${{secrets.CA_SSH_PRIVATE_KEY}}" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${{secrets.CA_USER_NAME}}@${{secrets.CA_HOST_IP}} "cd /var/www/html && git pull"